remote_theme: CaptainIRS/hacker-plus-theme

title: 4lv4r0t's Website
author: Alvaro Torres
description: Blog Website
disqus_forum_shortname: 4lv4r0t
google_site_verification_content: SrSDjNipQdYkPx063Fy8a8K3u5fndtW5pA8MqPVbPeU
google_analytics: # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: 1448981 # Go to the HackTheBox site and copy your ID
thm_badge_no: 1871792 # Go to https://tryhackme.com/profile -> Public Profile -> Get Badge ID
show_thm_htb_badges_in_nav: true
github_username: 4lv4r0t
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: alvaro-torres-b4ba79265/
twitch:
youtube:
twitter: 
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true
